### ISSUE TITLE
What technology or strategy should the system use to recommend the festival goers a festival with the highest match to their users preferences?

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#17]
# Description
What technology or strategy should the system use to recommend the festival goers a festival with the highest match to their users preferences?

# Tasks
- [x] Library: Available product analysis, Community research
- [x] Field: Problem analysis, Task analysis
- [x] Workshop: Brainstorm, Prototype
- [x] Lab: Non-functional test, Unit test

# Definition of done
- When the question is answered

# Links
-
