### ISSUE TITLE
What can a pair of collaborating Python agents do to ensure security between agents, while helping festival goers discovering, booking and managing festivals?

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#19]
# Description
What can a pair of collaborating Python agents do to ensure security between agents, while helping festival goers discovering, booking and managing festivals?

# Tasks
- [ ] Best good and bad practices, SWOT analysis
- [ ] Workshop: Code review
- [ ] Showroom: Static program analysis, Guideline conformity analysis

# Definition of done
- Answered

# Links
-
