### ISSUE TITLE
Festival Information Agent

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#2]
# Description
Create a Python bot using the GPT-4 API, that can be used for getting information about festivals.

# Tasks
- [x] Create custom system message to only allow knowledge of festivals.
- [x] Setup connection to GPT-4 API.
- [x] Create endpoint to get information about festivals.

# Definition of done
- Issue will be done once all above tasks are completed, and we have a functioning bot that can listen for available work.

# Links
- https://platform.openai.com/playground
