### ISSUE TITLE
Why do festival goers specifically within the age range of 18-28 require tailored recommendations for festivals?

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#20]
# Description
Why do festival goers specifically within the age range of 18-28 require tailored recommendations for festivals?

# Tasks
- [ ] Field: Focus group, Interview
- [ ] Library: Literature study
- [ ] Workshop: Gap analysis

# Definition of done
- Answered

# Links
-
