### ISSUE TITLE
Add Dashboard for managing API Keys Ticket system

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/ticket-system-agent#28]
# Description
For the Tickets system agents there needs to be a Dashboard where a User can manage their keys in order to use the API's.

# Tasks
- [x] Create new NextJS Project
- [x] Add Authentication 
- [x] Add login, register and logout functionality
- [x] Add Supabase Database for managing keys
- [x] Add simple dashboard

# Definition of done
- A NextJS Project is setup where you can get API keys for the ticket system agents
