### ISSUE TITLE
Design Ticket System Front-End

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#3]
# Description
For our ticket system application we want to have a good looking front-end, that gives information about the project to visitors.

# Tasks
- [ ] Design Front-End of Ticket System application
- [ ] Create interactive prototype from design
- [ ] Think about possible scenario's / scope

# Definition of done
- Once a valid design has been made, that also has an interactive prototype.

# Links
-
