### ISSUE TITLE
Setup CI for Festival Information Agent

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#32]
# Description
As we still have one agent to complete our scenario that does not yet have a CI or CD set up we want to add this to our to do list.

# Tasks
- [ ] Festival Information has CI
- [ ] CI includes tests
- [ ] CI includes performance tests

# Definition of done
- When CI is completely set up

# Links
-
