### ISSUE TITLE
Create Google Calendar Agent

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/ticket-system-agent#7]
# Description
For the festival information we want a bot to be able to add the 'booked' festival into someone's calendar.

# Tasks
- [ ] Research if this is possible, with an automatic agent
- [ ] Google Auth (is this even possible, as a bot?)
- [ ] As a bot add an event to someone's Google Calendar

# Definition of done
- Once it is possible to have a agent that can add an event to someone's Google calendar.

# Links
-
